defmodule Tunez.Repo.Migrations.AddFollowersNotifiedFlag do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:albums) do
      add :followers_notified, :boolean, null: false, default: false
    end
    # backfill existent albums to avoid users get notifications
    execute "UPDATE albums SET followers_notified = true"
  end

  def down do
    alter table(:albums) do
      remove :followers_notified
    end
  end
end
