defmodule Tunez.Repo.Migrations.AddUserFkRating do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:album_ratings, "album_ratings_user_id_fkey")

    alter table(:album_ratings) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "album_ratings_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create unique_index(:album_ratings, [:resource_id, :user_id],
             name: "album_ratings_unique_rating_index"
           )
  end

  def down do
    drop_if_exists unique_index(:album_ratings, [:resource_id, :user_id],
                     name: "album_ratings_unique_rating_index"
                   )

    drop constraint(:album_ratings, "album_ratings_user_id_fkey")

    alter table(:album_ratings) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "album_ratings_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
