defmodule Tunez.Repo.Migrations.FixRatingPrimaryKey do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint("artist_ratings", "artist_ratings_pkey")

    drop constraint("album_ratings", "album_ratings_pkey")

    drop_if_exists unique_index(:artist_ratings, [:resource_id, :user_id],
                     name: "artist_ratings_unique_rating_index"
                   )

    alter table(:artist_ratings) do
      modify :resource_id, :uuid, null: false
    end

    drop_if_exists unique_index(:album_ratings, [:resource_id, :user_id],
                     name: "album_ratings_unique_rating_index"
                   )

    alter table(:album_ratings) do
      modify :resource_id, :uuid, null: false
    end

    execute("ALTER TABLE \"album_ratings\" ADD PRIMARY KEY (resource_id, user_id)")

    execute("ALTER TABLE \"artist_ratings\" ADD PRIMARY KEY (resource_id, user_id)")
  end

  def down do
    drop constraint("artist_ratings", "artist_ratings_pkey")

    drop constraint("album_ratings", "album_ratings_pkey")

    alter table(:album_ratings) do
      modify :resource_id, :uuid, null: true
    end

    create unique_index(:album_ratings, [:resource_id, :user_id],
             name: "album_ratings_unique_rating_index"
           )

    alter table(:artist_ratings) do
      modify :resource_id, :uuid, null: true
    end

    create unique_index(:artist_ratings, [:resource_id, :user_id],
             name: "artist_ratings_unique_rating_index"
           )

    execute("ALTER TABLE \"album_ratings\" ADD PRIMARY KEY (user_id)")

    execute("ALTER TABLE \"artist_ratings\" ADD PRIMARY KEY (user_id)")
  end
end
