defmodule Tunez.Repo.Migrations.MakeAlbumsRateable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:album_ratings, primary_key: false) do
      add :rating, :bigint, default: 0

      add :resource_id,
          references(:albums, column: :id, name: "album_ratings_resource_id_fkey", type: :uuid)

      add :user_id,
          references(:users,
            column: :id,
            name: "album_ratings_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false
    end
  end

  def down do
    drop constraint(:album_ratings, "album_ratings_resource_id_fkey")

    drop constraint(:album_ratings, "album_ratings_user_id_fkey")

    drop table(:album_ratings)
  end
end
