defmodule Tunez.Repo.Migrations.MakeArtistRateable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:artist_ratings, primary_key: false) do
      add :rating, :bigint, default: 0

      add :resource_id,
          references(:artists, column: :id, name: "artist_ratings_resource_id_fkey", type: :uuid)

      add :user_id,
          references(:users,
            column: :id,
            name: "artist_ratings_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          primary_key: true,
          null: false
    end

    create unique_index(:artist_ratings, [:resource_id, :user_id],
             name: "artist_ratings_unique_rating_index"
           )
  end

  def down do
    drop_if_exists unique_index(:artist_ratings, [:resource_id, :user_id],
                     name: "artist_ratings_unique_rating_index"
                   )

    drop constraint(:artist_ratings, "artist_ratings_resource_id_fkey")

    drop constraint(:artist_ratings, "artist_ratings_user_id_fkey")

    drop table(:artist_ratings)
  end
end
